# StarDust CI Pipeline
# Designed for a protected main branch
# Only dev can be merged into main

name: StarDust CI

on:
  push:
    branches:
      - dev

  pull_request:
    branches:
      - main

jobs:
  test:
    name: Run tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Upgrade pip
        run: python -m pip install --upgrade pip

      - name: Install test dependencies
        run: |
          pip install pytest

      # Future-proof: when pyproject.toml is back
      # - name: Install StarDust
      #   run: pip install -e .

      - name: Run test suite
        run: |
          pytest
          echo "All tests passed!"